# syntax=docker/dockerfile@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769
FROM mcr.microsoft.com/vscode/devcontainers/base:debian

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN \
  apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  # Additional library needed by some tests and accordingly by VScode Tests Discovery
  bluez \
  ffmpeg \
  libudev-dev \
  libavformat-dev \
  libavcodec-dev \
  libavdevice-dev \
  libavutil-dev \
  libswscale-dev \
  libswresample-dev \
  libavfilter-dev \
  libpcap-dev \
  libturbojpeg0 \
  libyaml-dev \
  libxml2 \
  git \
  cmake \
  autoconf \
  # SAX Battery extras
  graphviz \
  libgammu-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Add go2rtc binary
COPY --from=ghcr.io/alexxit/go2rtc:latest /usr/local/bin/go2rtc /bin/go2rtc

WORKDIR /usr/src

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

USER vscode
ENV VIRTUAL_ENV="/home/vscode/.local/ha-venv"
RUN --mount=type=bind,source=.python-version,target=.python-version \
  uv python install \
  && uv venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install Python dependencies from this repository requirements
RUN --mount=type=bind,source=requirements.txt,target=requirements.txt \
  --mount=type=bind,source=requirements_dev.txt,target=requirements_dev.txt \
  --mount=type=bind,source=requirements_test.txt,target=requirements_test.txt \
  uv pip install -r requirements_test.txt

WORKDIR /workspaces

# Set the default shell to bash instead of sh
ENV SHELL=/bin/bash
