"""SunSpec-related entity definitions and constants for the SAX battery integration."""

from __future__ import annotations

from pymodbus.client.mixin import ModbusClientMixin

from .const import (
    DESCRIPTION_SAX_AC_CURRENT_A,
    DESCRIPTION_SAX_AC_CURRENT_B,
    DESCRIPTION_SAX_AC_CURRENT_C,
    DESCRIPTION_SAX_AC_CURRENT_SUM,
    DESCRIPTION_SAX_APPARENT_POWER,
    DESCRIPTION_SAX_CAPACITY,
    DESCRIPTION_SAX_CHARGE_POWER,
    DESCRIPTION_SAX_DEPTH_OF_DISCHARGE,
    DESCRIPTION_SAX_DISCHARGE_POWER,
    DESCRIPTION_SAX_GRID_FREQUENCY,
    DESCRIPTION_SAX_MAX_SOC,
    DESCRIPTION_SAX_MIN_SOC,
    DESCRIPTION_SAX_POWER,
    DESCRIPTION_SAX_POWER_FACTOR,
    DESCRIPTION_SAX_PV_POWER,
    DESCRIPTION_SAX_REACTIVE_POWER,
    DESCRIPTION_SAX_SCALE_FACTOR_AC_CURRENT,
    DESCRIPTION_SAX_SCALE_FACTOR_APPARENT_POWER,
    DESCRIPTION_SAX_SCALE_FACTOR_FREQUENCY,
    DESCRIPTION_SAX_SCALE_FACTOR_POWER,
    DESCRIPTION_SAX_SCALE_FACTOR_POWER_FACTOR,
    DESCRIPTION_SAX_SCALE_FACTOR_REACTIVE_POWER,
    DESCRIPTION_SAX_SCALE_FACTOR_VOLTAGE,
    DESCRIPTION_SAX_SMARTMETER_AC_CURRENT_SUM,
    DESCRIPTION_SAX_SMARTMETER_APPARENT_POWER,
    DESCRIPTION_SAX_SMARTMETER_CURRENT_L1,
    DESCRIPTION_SAX_SMARTMETER_CURRENT_L2,
    DESCRIPTION_SAX_SMARTMETER_CURRENT_L3,
    DESCRIPTION_SAX_SMARTMETER_FREQUENCY,
    DESCRIPTION_SAX_SMARTMETER_POWER_FACTOR,
    DESCRIPTION_SAX_SMARTMETER_POWER_L1,
    DESCRIPTION_SAX_SMARTMETER_POWER_L2,
    DESCRIPTION_SAX_SMARTMETER_POWER_L3,
    DESCRIPTION_SAX_SMARTMETER_REACTIVE_POWER,
    DESCRIPTION_SAX_SMARTMETER_TOTAL_POWER,
    DESCRIPTION_SAX_SMARTMETER_VOLTAGE_L1,
    DESCRIPTION_SAX_SMARTMETER_VOLTAGE_L1_L2,
    DESCRIPTION_SAX_SMARTMETER_VOLTAGE_L2,
    DESCRIPTION_SAX_SMARTMETER_VOLTAGE_L2_L3,
    DESCRIPTION_SAX_SMARTMETER_VOLTAGE_L3,
    DESCRIPTION_SAX_SMARTMETER_VOLTAGE_L3_L1,
    DESCRIPTION_SAX_SOC,
    DESCRIPTION_SAX_STATE,
    DESCRIPTION_SAX_SUNSPEC_REFERENCE_POWER,
    DESCRIPTION_SAX_SUNSPEC_SETPOINT_SCALE_FACTOR,
    DESCRIPTION_SAX_TEMPERATURE,
    DESCRIPTION_SAX_VOLTAGE_A,
    DESCRIPTION_SAX_VOLTAGE_B,
    DESCRIPTION_SAX_VOLTAGE_C,
    DESCRIPTION_SAX_VOLTAGE_L1_L2,
    DESCRIPTION_SAX_VOLTAGE_L2_L3,
    DESCRIPTION_SAX_VOLTAGE_L3_L1,
)
from .entity_keys import (
    SAX_AC_CURRENT_A,
    SAX_AC_CURRENT_B,
    SAX_AC_CURRENT_C,
    SAX_AC_CURRENT_SUM,
    SAX_CAPACITY,
    SAX_CHARGE_POWER,
    SAX_DEPTH_OF_DISCHARGE,
    SAX_DISCHARGE_POWER,
    SAX_GRID_FREQUENCY,
    SAX_MAX_SOC,
    SAX_MIN_SOC,
    SAX_POWER,
    SAX_POWER_FACTOR,
    SAX_PV_POWER,
    SAX_REACTIVE_POWER,
    SAX_SCALE_FACTOR_AC_CURRENT,
    SAX_SCALE_FACTOR_APPARENT_POWER,
    SAX_SCALE_FACTOR_FREQUENCY,
    SAX_SCALE_FACTOR_POWER,
    SAX_SCALE_FACTOR_POWER_FACTOR,
    SAX_SCALE_FACTOR_REACTIVE_POWER,
    SAX_SCALE_FACTOR_VOLTAGE,
    SAX_SMARTMETER_AC_CURRENT_SUM,
    SAX_SMARTMETER_APPARENT_POWER,
    SAX_SMARTMETER_CURRENT_L1,
    SAX_SMARTMETER_CURRENT_L2,
    SAX_SMARTMETER_CURRENT_L3,
    SAX_SMARTMETER_FREQUENCY,
    SAX_SMARTMETER_POWER_FACTOR,
    SAX_SMARTMETER_POWER_L1,
    SAX_SMARTMETER_POWER_L2,
    SAX_SMARTMETER_POWER_L3,
    SAX_SMARTMETER_REACTIVE_POWER,
    SAX_SMARTMETER_TOTAL_POWER,
    SAX_SMARTMETER_VOLTAGE_L1,
    SAX_SMARTMETER_VOLTAGE_L1_L2,
    SAX_SMARTMETER_VOLTAGE_L2,
    SAX_SMARTMETER_VOLTAGE_L2_L3,
    SAX_SMARTMETER_VOLTAGE_L3,
    SAX_SMARTMETER_VOLTAGE_L3_L1,
    SAX_SOC,
    SAX_STATE,
    SAX_SUNSPEC_CONTROL_MODE,
    SAX_SUNSPEC_POWER_SETPOINT,
    SAX_SUNSPEC_REFERENCE_POWER,
    SAX_SUNSPEC_SETPOINT_SCALE_FACTOR,
    SAX_SUNSPEC_SETPOINT_TIMEOUT,
    SAX_TEMPERATURE,
    SAX_VOLTAGE_A,
    SAX_VOLTAGE_B,
    SAX_VOLTAGE_C,
    SAX_VOLTAGE_L1_L2,
    SAX_VOLTAGE_L2_L3,
    SAX_VOLTAGE_L3_L1,
    SUNSPEC_APPARENT_POWER,
    SUNSPEC_AVERAGE_CELL_VOLTAGE,
    SUNSPEC_CELL_EVENT,
    SUNSPEC_CHARGE_STATUS,
    SUNSPEC_DEVICE_MODEL_1,
    SUNSPEC_DEVICE_MODEL_2,
    SUNSPEC_DEVICE_MODEL_3,
    SUNSPEC_EVENT,
    SUNSPEC_MANUFACTURER_1,
    SUNSPEC_MANUFACTURER_2,
    SUNSPEC_MANUFACTURER_3,
    SUNSPEC_MANUFACTURER_4,
    SUNSPEC_RESERVED_40039,
    SUNSPEC_RESERVED_40040,
    SUNSPEC_RESERVED_40104,
    SUNSPEC_RESERVED_40105,
    SUNSPEC_RESERVED_40107,
    SUNSPEC_RESERVED_40113,
    SUNSPEC_SERIAL_NUMBER_HIGH,
    SUNSPEC_SERIAL_NUMBER_LOW,
    SUNSPEC_SM_APPARENT_POWER_L1,
    SUNSPEC_SM_APPARENT_POWER_L2,
    SUNSPEC_SM_APPARENT_POWER_L3,
    SUNSPEC_SM_POWER_FACTOR_L1,
    SUNSPEC_SM_POWER_FACTOR_L2,
    SUNSPEC_SM_POWER_FACTOR_L3,
    SUNSPEC_SM_REACTIVE_POWER_L1,
    SUNSPEC_SM_REACTIVE_POWER_L2,
    SUNSPEC_SM_REACTIVE_POWER_L3,
    SUNSPEC_SM_RESERVED_40092,
    SUNSPEC_SM_RESERVED_40093,
    SUNSPEC_SM_RESERVED_40094,
    SUNSPEC_SM_VOLTAGE_LL_AVERAGE,
    SUNSPEC_SM_VOLTAGE_LN_AVERAGE,
    SUNSPEC_VERSION_GATEWAY,
    SUNSPEC_VERSION_MASTER,
)
from .enums import DeviceConstants, TypeConstants
from .items import ModbusItem

# SunSpec protocol identifiers and model IDs
SUNSPEC_ID_WORD_0 = 21365
SUNSPEC_ID_WORD_1 = 28243
SUNSPEC_MODEL_COMMON = 1
SUNSPEC_MODEL_INVERTER = 103
SUNSPEC_MODEL_IMMEDIATE_CONTROLS = 123
SUNSPEC_MODEL_METER = 203
SUNSPEC_MODEL_BATTERY_BASE = 802

# fmt: off

# Common model (metadata only) - SunSpecID / Model-ID / Length rows are intentionally ignored
SUNSPEC_COMMON_MODEL_ITEMS: list[ModbusItem] = [
    ModbusItem(battery_device_id=100, address=40004, name=SUNSPEC_MANUFACTURER_1, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40005, name=SUNSPEC_MANUFACTURER_2, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40006, name=SUNSPEC_MANUFACTURER_3, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40007, name=SUNSPEC_MANUFACTURER_4, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40008, name=SUNSPEC_DEVICE_MODEL_1, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40009, name=SUNSPEC_DEVICE_MODEL_2, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40010, name=SUNSPEC_DEVICE_MODEL_3, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40011, name=SUNSPEC_VERSION_MASTER, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40012, name=SUNSPEC_VERSION_GATEWAY, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40013, name=SUNSPEC_SERIAL_NUMBER_HIGH, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40014, name=SUNSPEC_SERIAL_NUMBER_LOW, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.BESS, ),
]

# Model 103 (3ph inverter / battery electronics)
SUNSPEC_INVERTER_MODEL_ITEMS: list[ModbusItem] = [
    ModbusItem(battery_device_id=100, address=40017, name=SAX_AC_CURRENT_SUM, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40021", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_AC_CURRENT_SUM, translation_key="bess_ac_current_sum", ),
    ModbusItem(battery_device_id=100, address=40018, name=SAX_AC_CURRENT_A, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40021", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_AC_CURRENT_A, translation_key="bess_ac_current_a", ),
    ModbusItem(battery_device_id=100, address=40019, name=SAX_AC_CURRENT_B, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40021", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_AC_CURRENT_B, translation_key="bess_ac_current_b", ),
    ModbusItem(battery_device_id=100, address=40020, name=SAX_AC_CURRENT_C, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40021", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_AC_CURRENT_C, translation_key="bess_ac_current_c", ),
    ModbusItem(battery_device_id=100, address=40021, name="sunspec_sf_ac_current", mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40022, name=SAX_VOLTAGE_L1_L2, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40028", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_VOLTAGE_L1_L2, translation_key="bess_voltage_l1_l2", ),
    ModbusItem(battery_device_id=100, address=40023, name=SAX_VOLTAGE_L2_L3, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40028", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_VOLTAGE_L2_L3, translation_key="bess_voltage_l2_l3", ),
    ModbusItem(battery_device_id=100, address=40024, name=SAX_VOLTAGE_L3_L1, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40028", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_VOLTAGE_L3_L1, translation_key="bess_voltage_l3_l1", ),
    ModbusItem(battery_device_id=100, address=40025, name=SAX_VOLTAGE_A, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40028", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_VOLTAGE_A, translation_key="bess_voltage_a", ),
    ModbusItem(battery_device_id=100, address=40026, name=SAX_VOLTAGE_B, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40028", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_VOLTAGE_B, translation_key="bess_voltage_b", ),
    ModbusItem(battery_device_id=100, address=40027, name=SAX_VOLTAGE_C, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40028", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_VOLTAGE_C, translation_key="bess_voltage_c", ),
    ModbusItem(battery_device_id=100, address=40028, name="sunspec_sf_voltage", mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40029, name=SAX_POWER, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, scale_factor_ref="R40030", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_POWER, translation_key="bess_power", ),
    ModbusItem(battery_device_id=100, address=40030, name="sunspec_sf_power", mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40031, name=SAX_GRID_FREQUENCY, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40032", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_GRID_FREQUENCY, translation_key="bess_grid_frequency", ),
    ModbusItem(battery_device_id=100, address=40032, name="sunspec_sf_frequency", mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40033, name=SUNSPEC_APPARENT_POWER, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40034", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_APPARENT_POWER, translation_key="bess_apparent_power", ),
    ModbusItem(battery_device_id=100, address=40034, name="sunspec_sf_apparent_power", mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40035, name=SAX_REACTIVE_POWER, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, scale_factor_ref="R40036", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_REACTIVE_POWER, translation_key="bess_reactive_power", ),
    ModbusItem(battery_device_id=100, address=40036, name="sunspec_sf_reactive_power", mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40037, name=SAX_POWER_FACTOR, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, scale_factor_ref="R40038", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_POWER_FACTOR, translation_key="bess_power_factor", ),
    ModbusItem(battery_device_id=100, address=40038, name="sunspec_sf_power_factor", mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40039, name=SUNSPEC_RESERVED_40039, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40040, name=SUNSPEC_RESERVED_40040, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40041, name=SAX_TEMPERATURE, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, scale_factor_ref="R40042", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_TEMPERATURE, translation_key="bess_temperature", ),
    ModbusItem(battery_device_id=100, address=40042, name="sunspec_sf_temperatur", mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40043, name=SAX_STATE, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, state_map={1: "Off", 2: "Standby", 3: "Waiting", 4: "On", 7: "SM-Error"}, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_STATE, translation_key="bess_state", ),
    ModbusItem(battery_device_id=100, address=40044, name=SUNSPEC_EVENT, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40045, name=SAX_PV_POWER, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40046", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_PV_POWER, translation_key="bess_pv_power", ),
    ModbusItem(battery_device_id=100, address=40046, name="sunspec_sf_pv_power", mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.BESS, ),
]

# Model 123 (immediate controls)
SUNSPEC_IMMEDIATE_CONTROL_ITEMS: list[ModbusItem] = [
    ModbusItem(battery_device_id=100, address=40049, name=SAX_SUNSPEC_POWER_SETPOINT, mtype=TypeConstants.NUMBER, data_type=ModbusClientMixin.DATATYPE.INT16, scale_factor_ref="R40052", factor=1.0, device=DeviceConstants.SYS, translation_key="sunspec_power_setpoint", ),
    ModbusItem(battery_device_id=100, address=40050, name=SAX_SUNSPEC_SETPOINT_TIMEOUT, mtype=TypeConstants.NUMBER, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.SYS, translation_key="sunspec_setpoint_timeout", ),
    ModbusItem(battery_device_id=100, address=40051, name=SAX_SUNSPEC_CONTROL_MODE, mtype=TypeConstants.NUMBER, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.SYS, translation_key="sunspec_control_mode", ),
    ModbusItem(battery_device_id=100, address=40052, name=SAX_SUNSPEC_SETPOINT_SCALE_FACTOR, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.SYS, entitydescription=DESCRIPTION_SAX_SUNSPEC_SETPOINT_SCALE_FACTOR, translation_key="sunspec_setpoint_scale_factor", ),
    ModbusItem(battery_device_id=100, address=40053, name=SAX_SUNSPEC_REFERENCE_POWER, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.SYS, entitydescription=DESCRIPTION_SAX_SUNSPEC_REFERENCE_POWER, translation_key="sunspec_reference_power", ),
]

# Model 203 (smart meter)
SUNSPEC_METER_MODEL_ITEMS: list[ModbusItem] = [
    ModbusItem(battery_device_id=100, address=40056, name=SAX_SMARTMETER_AC_CURRENT_SUM, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40060", factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SMARTMETER_AC_CURRENT_SUM, translation_key="sm_ac_current_sum", ),
    ModbusItem(battery_device_id=100, address=40057, name=SAX_SMARTMETER_CURRENT_L1, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40060", factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SMARTMETER_CURRENT_L1, translation_key="sm_current_l1", ),
    ModbusItem(battery_device_id=100, address=40058, name=SAX_SMARTMETER_CURRENT_L2, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40060", factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SMARTMETER_CURRENT_L2, translation_key="sm_current_l2", ),
    ModbusItem(battery_device_id=100, address=40059, name=SAX_SMARTMETER_CURRENT_L3, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40060", factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SMARTMETER_CURRENT_L3, translation_key="sm_current_l3", ),
    ModbusItem(battery_device_id=100, address=40060, name=SAX_SCALE_FACTOR_AC_CURRENT, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SCALE_FACTOR_AC_CURRENT, translation_key="sm_scale_factor_ac_current", ),
    ModbusItem(battery_device_id=100, address=40061, name=SUNSPEC_SM_VOLTAGE_LN_AVERAGE, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40069", factor=1.0, device=DeviceConstants.SM, ),
    ModbusItem(battery_device_id=100, address=40062, name=SAX_SMARTMETER_VOLTAGE_L1, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40069", factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SMARTMETER_VOLTAGE_L1, translation_key="sm_voltage_l1", ),
    ModbusItem(battery_device_id=100, address=40063, name=SAX_SMARTMETER_VOLTAGE_L2, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40069", factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SMARTMETER_VOLTAGE_L2, translation_key="sm_voltage_l2", ),
    ModbusItem(battery_device_id=100, address=40064, name=SAX_SMARTMETER_VOLTAGE_L3, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40069", factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SMARTMETER_VOLTAGE_L3, translation_key="sm_voltage_l3", ),
    ModbusItem(battery_device_id=100, address=40065, name=SUNSPEC_SM_VOLTAGE_LL_AVERAGE, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40069", factor=1.0, device=DeviceConstants.SM, ),
    ModbusItem(battery_device_id=100, address=40066, name=SAX_SMARTMETER_VOLTAGE_L1_L2, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40069", factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SMARTMETER_VOLTAGE_L1_L2, translation_key="sm_voltage_l1_l2", ),
    ModbusItem(battery_device_id=100, address=40067, name=SAX_SMARTMETER_VOLTAGE_L2_L3, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40069", factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SMARTMETER_VOLTAGE_L2_L3, translation_key="sm_voltage_l2_l3", ),
    ModbusItem(battery_device_id=100, address=40068, name=SAX_SMARTMETER_VOLTAGE_L3_L1, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40069", factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SMARTMETER_VOLTAGE_L3_L1, translation_key="sm_voltage_l3_l1", ),
    ModbusItem(battery_device_id=100, address=40069, name=SAX_SCALE_FACTOR_VOLTAGE, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SCALE_FACTOR_VOLTAGE, translation_key="sm_scale_factor_voltage", ),
    ModbusItem(battery_device_id=100, address=40070, name=SAX_SMARTMETER_FREQUENCY, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40071", factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SMARTMETER_FREQUENCY, translation_key="sm_frequency", ),
    ModbusItem(battery_device_id=100, address=40071, name=SAX_SCALE_FACTOR_FREQUENCY, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SCALE_FACTOR_FREQUENCY, translation_key="sm_scale_factor_frequency", ),
    ModbusItem(battery_device_id=100, address=40072, name=SAX_SMARTMETER_TOTAL_POWER, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, scale_factor_ref="R40076", factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SMARTMETER_TOTAL_POWER, translation_key="sm_total_power", ),
    ModbusItem(battery_device_id=100, address=40073, name=SAX_SMARTMETER_POWER_L1, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, scale_factor_ref="R40076", factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SMARTMETER_POWER_L1, translation_key="sm_power_l1", ),
    ModbusItem(battery_device_id=100, address=40074, name=SAX_SMARTMETER_POWER_L2, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, scale_factor_ref="R40076", factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SMARTMETER_POWER_L2, translation_key="sm_power_l2", ),
    ModbusItem(battery_device_id=100, address=40075, name=SAX_SMARTMETER_POWER_L3, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, scale_factor_ref="R40076", factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SMARTMETER_POWER_L3, translation_key="sm_power_l3", ),
    ModbusItem(battery_device_id=100, address=40076, name=SAX_SCALE_FACTOR_POWER, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SCALE_FACTOR_POWER, translation_key="sm_scale_factor_power", ),
    ModbusItem(battery_device_id=100, address=40077, name=SAX_SMARTMETER_APPARENT_POWER, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40081", factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SMARTMETER_APPARENT_POWER, translation_key="sm_apparent_power", ),
    ModbusItem(battery_device_id=100, address=40078, name=SUNSPEC_SM_APPARENT_POWER_L1, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40081", factor=1.0, device=DeviceConstants.SM, ),
    ModbusItem(battery_device_id=100, address=40079, name=SUNSPEC_SM_APPARENT_POWER_L2, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40081", factor=1.0, device=DeviceConstants.SM, ),
    ModbusItem(battery_device_id=100, address=40080, name=SUNSPEC_SM_APPARENT_POWER_L3, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40081", factor=1.0, device=DeviceConstants.SM, ),
    ModbusItem(battery_device_id=100, address=40081, name=SAX_SCALE_FACTOR_APPARENT_POWER, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SCALE_FACTOR_APPARENT_POWER, translation_key="sm_scale_factor_apparent_power", ),
    ModbusItem(battery_device_id=100, address=40082, name=SAX_SMARTMETER_REACTIVE_POWER, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, scale_factor_ref="R40086", factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SMARTMETER_REACTIVE_POWER, translation_key="sm_reactive_power", ),
    ModbusItem(battery_device_id=100, address=40083, name=SUNSPEC_SM_REACTIVE_POWER_L1, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, scale_factor_ref="R40086", factor=1.0, device=DeviceConstants.SM, ),
    ModbusItem(battery_device_id=100, address=40084, name=SUNSPEC_SM_REACTIVE_POWER_L2, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, scale_factor_ref="R40086", factor=1.0, device=DeviceConstants.SM, ),
    ModbusItem(battery_device_id=100, address=40085, name=SUNSPEC_SM_REACTIVE_POWER_L3, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, scale_factor_ref="R40086", factor=1.0, device=DeviceConstants.SM, ),
    ModbusItem(battery_device_id=100, address=40086, name=SAX_SCALE_FACTOR_REACTIVE_POWER, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SCALE_FACTOR_REACTIVE_POWER, translation_key="sm_scale_factor_reactive_power", ),
    ModbusItem(battery_device_id=100, address=40087, name=SAX_SMARTMETER_POWER_FACTOR, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, scale_factor_ref="R40091", factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SMARTMETER_POWER_FACTOR, translation_key="sm_power_factor", ),
    ModbusItem(battery_device_id=100, address=40088, name=SUNSPEC_SM_POWER_FACTOR_L1, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, scale_factor_ref="R40091", factor=1.0, device=DeviceConstants.SM, ),
    ModbusItem(battery_device_id=100, address=40089, name=SUNSPEC_SM_POWER_FACTOR_L2, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, scale_factor_ref="R40091", factor=1.0, device=DeviceConstants.SM, ),
    ModbusItem(battery_device_id=100, address=40090, name=SUNSPEC_SM_POWER_FACTOR_L3, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, scale_factor_ref="R40091", factor=1.0, device=DeviceConstants.SM, ),
    ModbusItem(battery_device_id=100, address=40091, name=SAX_SCALE_FACTOR_POWER_FACTOR, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.SM, entitydescription=DESCRIPTION_SAX_SCALE_FACTOR_POWER_FACTOR, translation_key="sm_scale_factor_power_factor", ),
    ModbusItem(battery_device_id=100, address=40092, name=SUNSPEC_SM_RESERVED_40092, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.SM, ),
    ModbusItem(battery_device_id=100, address=40093, name=SUNSPEC_SM_RESERVED_40093, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.SM, ),
    ModbusItem(battery_device_id=100, address=40094, name=SUNSPEC_SM_RESERVED_40094, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.SM, ),
]

# Model 802 (battery base model)
SUNSPEC_BATTERY_BASE_MODEL_ITEMS: list[ModbusItem] = [
    ModbusItem(battery_device_id=100, address=40097, name=SAX_CAPACITY, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40110", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_CAPACITY, translation_key="bess_capacity", ),
    ModbusItem(battery_device_id=100, address=40098, name=SAX_CHARGE_POWER, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40111", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_CHARGE_POWER, translation_key="bess_charge_power", ),
    ModbusItem(battery_device_id=100, address=40099, name=SAX_DISCHARGE_POWER, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40111", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_DISCHARGE_POWER, translation_key="bess_discharge_power", ),
    ModbusItem(battery_device_id=100, address=40100, name=SAX_MAX_SOC, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40112", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_MAX_SOC, translation_key="bess_max_soc", ),
    ModbusItem(battery_device_id=100, address=40101, name=SAX_MIN_SOC, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40112", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_MIN_SOC, translation_key="bess_min_soc", ),
    ModbusItem(battery_device_id=100, address=40102, name=SAX_SOC, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40112", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_SOC, translation_key="bess_soc", ),
    ModbusItem(battery_device_id=100, address=40103, name=SAX_DEPTH_OF_DISCHARGE, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40112", factor=1.0, device=DeviceConstants.BESS, entitydescription=DESCRIPTION_SAX_DEPTH_OF_DISCHARGE, translation_key="bess_depth_of_discharge", ),
    ModbusItem(battery_device_id=100, address=40104, name=SUNSPEC_RESERVED_40104, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40105, name=SUNSPEC_RESERVED_40105, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40106, name=SUNSPEC_CHARGE_STATUS, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, state_map={0: "No Power", 1: "Power Applied"}, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40107, name=SUNSPEC_RESERVED_40107, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40108, name=SUNSPEC_CELL_EVENT, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, factor=1.0, state_map={0: "Normal Operation", 3: "Overtemperature", 4: "Undertemperature"}, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40109, name=SUNSPEC_AVERAGE_CELL_VOLTAGE, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.UINT16, scale_factor_ref="R40114", factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40110, name="sunspec_sf_capacity", mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40111, name="sunspec_sf_charge_discharge_power", mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40112, name="sunspec_sf_soc", mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40113, name=SUNSPEC_RESERVED_40113, mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.BESS, ),
    ModbusItem(battery_device_id=100, address=40114, name="sunspec_sf_cell_voltage", mtype=TypeConstants.SENSOR, data_type=ModbusClientMixin.DATATYPE.INT16, factor=1.0, device=DeviceConstants.BESS, ),
]

# fmt: on

SUNSPEC_ITEM_BLOCKS: dict[str, list[ModbusItem]] = {
    "common_model": SUNSPEC_COMMON_MODEL_ITEMS,
    "inverter_model": SUNSPEC_INVERTER_MODEL_ITEMS,
    "immediate_controls": SUNSPEC_IMMEDIATE_CONTROL_ITEMS,
    "meter_model": SUNSPEC_METER_MODEL_ITEMS,
    "battery_base_model": SUNSPEC_BATTERY_BASE_MODEL_ITEMS,
}

MODBUS_SUNSPEC_ITEMS: list[ModbusItem] = [
    *SUNSPEC_COMMON_MODEL_ITEMS,
    *SUNSPEC_INVERTER_MODEL_ITEMS,
    *SUNSPEC_IMMEDIATE_CONTROL_ITEMS,
    *SUNSPEC_METER_MODEL_ITEMS,
    *SUNSPEC_BATTERY_BASE_MODEL_ITEMS,
]


def get_canonical_sunspec_items_by_name() -> dict[str, ModbusItem]:
    """Return canonical SunSpec items keyed by item name."""
    return {item.name: item for item in MODBUS_SUNSPEC_ITEMS}
