#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

sudo apt-get update
sudo apt-get install -y --no-install-recommends \
    libpcap-dev \
    libturbojpeg0
python3 -m pip install -r requirements_test.txt --upgrade
pre-commit install
